version: '3'

services: 

  nginx:
    build: 
      context: nginx
    container_name: nginx
    networks: 
      - app-network
    tty: true
    ports: 
      - "8080:80"
    depends_on: 
       - db
       - app

  app:
    build: 
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks: 
      - app-network
    command: 'node index.js'
    tty: true
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - app-network

networks: 
  app-network:
    driver: bridge      
